version: '3.8'

services:
  ui:
    build: 
      dockerfile: packages/client/Dockerfile
      context: "./"
    env_file:
      - packages/client/.env
    ports: 
      - 3000:3000
    depends_on:
      - api
  api: 
    build: 
      dockerfile: packages/backend/Dockerfile
      context: "./"
      args:
        PGSQL_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DATABASE}
        SERVER_PORT: ${SERVER_PORT}
    env_file:
      - packages/backend/.env
    ports:
      - 4001:4001
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

volumes:
  pgdata: